Feature/db
pvb-fs/node-test pull request #2
Opened 2022-04-11 12:57 UTC by PVBalyuk

created connection with MySQL through sequelize

2022-04-12 05:12 UTC, khikhlun-itransition commented
На сиквалайз не установлены типы, для этого поставь https://www.npmjs.com/package/@types/sequelize (это даже линтер подсвчивает в редакторе кода. Если у тебя не подсвечивается, то установи eslint плагин для редактора)

2022-04-12 05:23 UTC, khikhlun-itransition requested changes

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/database/database.ts
> +const sequelize = new Sequelize('node_test', 'root', '12345678', {
Задавать креды для БД в явном виде - не лучшая затея. Почитай, что такое пременные окружения и создай .env.local файл(не забудь его добавить в гит игнор) и определи там переменные для бд, а также создай .env.template файл, где определи названия необходимых переменных(этот файл уже в гит игнор добавляться не будет)

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/database/database.ts
> +// import Customer from './models/customer';
Комментариев кода, без объяснения почему он закомменчен, быть не должно

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/database/main.ts
> +import sequelize from './database';
Название файл как main.ts не является удачным. Лучше назвать как-нибудь наподобие initializeDatabase

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/database/main.ts
> +export const syncModels = async () => {
Если переименуешь файл на initializeDatabase, то и методу дай аналогичное название

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/database/main.ts
> +    .catch((error) => console.log(error));
Передача колбека избыточна, можно просто передать console.log
`.catch(console.log);`

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/database/models/customer.ts
> +  'Customer',
Лучше не плодить строковые литералы для названий моделей. Создай отдельный файл с константой или енамом, назвав его что-то типо dbModelNames и используй переменную вместо явной строки

2022-04-12 05:23 UTC, khikhlun-itransition commented on src/index.ts
> +import express from 'express';
В index.ts я хотел бы видеть вызов лишь одного метода под названием startup или bootstrap(можешь прямо рядом создать файл с таким названием, нде и будет распологаться данный метод), внутри которого уже и будет инициализация всего что нужно(в твоем случае это инициализация бд и экспресс сервера)

2022-04-12 09:30 UTC, PVBalyuk commented on src/database/database.ts
> +const sequelize = new Sequelize('node_test', 'root', '12345678', {
done!

2022-04-12 09:30 UTC, PVBalyuk commented on src/database/database.ts
> +// import Customer from './models/customer';
done!

2022-04-12 09:30 UTC, PVBalyuk commented on src/database/main.ts
> +import sequelize from './database';
done!

2022-04-12 09:30 UTC, pvb-fs commented on src/database/main.ts
> +export const syncModels = async () => {
done!

2022-04-12 09:31 UTC, PVBalyuk commented on src/database/main.ts
> +    .catch((error) => console.log(error));
done!

2022-04-12 09:31 UTC, PVBalyuk commented on src/database/models/customer.ts
> +  'Customer',
done!

2022-04-12 09:31 UTC, PVBalyuk commented on src/index.ts
> +import express from 'express';
done!

2022-04-13 05:42 UTC, khikhlun-itransition commented on src/database/models/dbModelNames.ts
> +export const dbModelNames: IdbModelName = {
Лучше поменять на енам
```
enum DbModelNames {
  Customer: 'Customer',
  Order: 'Order'
}
```

2022-04-14 05:59 UTC, khikhlun-itransition approved these changes

2022-04-14 06:19 UTC, merged