Feature/auth
pvb-fs/node-test pull request #3
Opened 2022-04-14 11:58 UTC by PVBalyuk

2022-04-15 06:07 UTC, khikhlun-itransition requested changes

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/app.ts
> +    console.log(e);
console.error(e);

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/authController.ts
> +interface Dec {
Не лучший нейминг. Непонятно, что значит Dec. Плюс лучше в начале интерфейсов добавлять I. IDec (в данном случае)

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/authController.ts
> +dotenv.config({ path: envpath });
Контроллер - точно не то место, где конфиг doenv не должен происходить

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/authController.ts
> +      const u = await Customer.findOne({ where: { firstName: req.body.firstName } });
Давай более понятные имена. Что такое `u` не особо понятно

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/authController.ts
> +      if (!validPass) return res.status(400).json('Неверный пароль');
Определи для себя, какой вариант if тебе по больше по душе и придерживайся одного стиля
`if (условие) return что-то`
либо
```
if (условие) {
  return что-то
}
```

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/database/database.ts
> +dotenv.config({ path: envpath });
Почему-то у тебя конфигурация env в нескольких места, что нехорошо

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/database/database.ts
> +const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_LOGIN, process.env.DB_PASSWORD, {
Го создадим папочку confing, в которой будут определения конфигурация.
В твоем кейсе будет 2 файла: db-confing.ts и auth-config.ts
Пример db-config:
export const DB_CONFIG = {
 dbName: process.env.DB_NAME,
 login: process.env.DB_LOGIN,
  ....
}
И используешь эту константу вместо process.env

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/database/models.ts
> +// import Order from './models/order';
Помним то, что я говорил про закомменченный код

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/database/models/dbModelNames.ts
> +export enum dbModelNames {
Как правило, енамы именуются с большой буквы

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/index.ts
> +bootstrap();
Добавь это eslint правило в конфиг линта "eol-last": ["error", "always"]

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/index.ts
> +bootstrap();
Можешь еще добавить эти
https://eslint.org/docs/rules/newline-after-var
https://eslint.org/docs/rules/newline-before-return

2022-04-15 06:07 UTC, khikhlun-itransition commented on src/authController.ts
> +import { Response, Request } from 'express';
У тебя контроллер и роутер лежат на одном уровне с index.ts. Создай под это дело отдельную папочку

2022-04-15 07:16 UTC, PVBalyuk commented on src/app.ts
> +    console.log(e);
done

2022-04-15 07:24 UTC, PVBalyuk commented on src/authController.ts
> +interface Dec {
done

2022-04-15 07:24 UTC, PVBalyuk commented on src/authController.ts
> +      const u = await Customer.findOne({ where: { firstName: req.body.firstName } });
done

2022-04-15 07:26 UTC, PVBalyuk commented on src/authController.ts
> +      if (!validPass) return res.status(400).json('Неверный пароль');
done

2022-04-15 07:37 UTC, PVBalyuk commented on src/authController.ts
> +dotenv.config({ path: envpath });
done

2022-04-15 07:37 UTC, PVBalyuk commented on src/database/database.ts
> +dotenv.config({ path: envpath });
done

2022-04-15 07:37 UTC, PVBalyuk commented on src/database/database.ts
> +const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_LOGIN, process.env.DB_PASSWORD, {
done

2022-04-15 07:39 UTC, PVBalyuk commented on src/database/models.ts
> +// import Order from './models/order';
done

2022-04-15 07:41 UTC, PVBalyuk commented on src/database/models/dbModelNames.ts
> +export enum dbModelNames {
done

2022-04-15 07:57 UTC, PVBalyuk commented on src/authController.ts
> +import { Response, Request } from 'express';
done

2022-04-15 07:57 UTC, PVBalyuk commented on src/index.ts
> +bootstrap();
done

2022-04-19 05:50 UTC, khikhlun-itransition requested changes

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/services/token-utils.ts
> +  const accessToken = jwt.sign(payload, SECRET_KEY_CONFIG.secretKeyAccess, { expiresIn: '15m' });
Время истечения токена тоже можешь в SECRET_KEY_CONFIG закинуть, но уже не через process.env

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/services/token-utils.ts
> +import jwt, { JwtPayload } from 'jsonwebtoken';
JwtPayload заимпорчен, но нигде не используется

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/registation.ts
> +  try {
Внешний try catch необязателен, так как если что-то упадет, то експресс сам кинет ошибку

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/registation.ts
> +    const hashedPassword = await hashPassword(req.body.password, 5);
Старайся не использовать магических чисел. По хорошему, соль должна тоже в конфиге лежать

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/registation.ts
> +    const errors = validationResult(req);
Создай мидлвару, которая не пустит в сам контроллер, если валидация не пройдена

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/registation.ts
> +      return res.status(200).json({ message: 'Ошибки при регистрации', errors });
Код ошибки не должен быть 200, так как запрос не отработал успешно

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/registation.ts
> +    return res.status(200).json({ message: 'successful' });
Попробуй просто res.json({ message: 'successful' });
Предполагаю, что он по дефолту засетит 200 код

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/refresh-token.ts
> +    const decoded: IDecodedToken = jwt_decode(refreshTokenFromDB);
jwt_decode должен быть инкапсулирован в токен сервисе и не юзаться явно

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/refresh-token.ts
> +    if (!user) {
Повычищай, плз, ненужные проверки по аналогии как я тебе рассказывал вчера

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/refresh-token.ts
> +    if (!expiresAt) {
Проверка на то, что токен заэкспайрился должна быть в токен сервисе

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/modules/auth/handlers/login.ts
> +    const validPass = await validatePassword(req.body.password, userEmailCheck.get().password);
Базовый конвеншен к неймингу булеанов - это то, что они начинаются с is/are/has..., чтоб быстро различать переменные не вникая в тип. Переменная должна называться наподобие isPasswordValid

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/config/auth-config.ts
> +dotenv.config({ path: envPath });
А это обязательно делать dotenv.config({ path: envPath }); в каждом файле ?По логике ты в app.ts это пропишешь и он должен везде env подхватывать

2022-04-19 05:50 UTC, khikhlun-itransition commented on src/app.ts
> +    app.listen(3000, () => {
Порт затолкай тоже в .env

2022-04-19 06:42 UTC, PVBalyuk commented on src/services/token-utils.ts
> +  const accessToken = jwt.sign(payload, SECRET_KEY_CONFIG.secretKeyAccess, { expiresIn: '15m' });
done

2022-04-19 06:42 UTC, PVBalyuk commented on src/services/token-utils.ts
> +import jwt, { JwtPayload } from 'jsonwebtoken';
done

2022-04-19 06:43 UTC, PVBalyuk commented on src/modules/auth/handlers/registation.ts
> +  try {
done

2022-04-19 06:55 UTC, PVBalyuk commented on src/modules/auth/handlers/registation.ts
> +    const hashedPassword = await hashPassword(req.body.password, 5);
done

2022-04-19 07:10 UTC, PVBalyuk commented on src/modules/auth/handlers/registation.ts
> +    const errors = validationResult(req);
done

2022-04-19 07:29 UTC, PVBalyuk commented on src/modules/auth/handlers/refresh-token.ts
> +    if (!expiresAt) {
done

2022-04-19 07:30 UTC, PVBalyuk commented on src/modules/auth/handlers/login.ts
> +    const validPass = await validatePassword(req.body.password, userEmailCheck.get().password);
done

2022-04-19 07:32 UTC, PVBalyuk commented on src/config/auth-config.ts
> +dotenv.config({ path: envPath });
done

2022-04-19 07:38 UTC, PVBalyuk commented on src/app.ts
> +    app.listen(3000, () => {
done

2022-04-20 06:25 UTC, khikhlun-itransition requested changes

2022-04-20 06:25 UTC, khikhlun-itransition commented on src/modules/auth/handlers/login.ts
> +  const isValidPass = await validatePassword(req.body.password, userEmailCheck.get().password);
Почему бы не достать password из userEmailCheck строкой выше, чем писать userEmailCheck.get().password ?

2022-04-20 06:25 UTC, khikhlun-itransition commented on src/modules/auth/handlers/login.ts
> +  await Customer.update({ refreshToken: token.refreshToken }, { where: { email: req.body.email } });
Вместо того, что писать в нескольких местах req.body.email, email можно достать через деструктуризацию в начале метода

2022-04-20 06:25 UTC, khikhlun-itransition commented on src/modules/auth/handlers/login.ts
> +  res.status(200).json(`id${id} ${firstName} ${secondName} ${email} Refresh token - ${token.refreshToken}`);
На фронте нужен объект с данными, а не строка

2022-04-20 06:25 UTC, khikhlun-itransition commented on src/modules/auth/handlers/refresh-token.ts
> +  const email = user.get().email;
const { email } = user.get();

2022-04-20 06:25 UTC, khikhlun-itransition commented on src/modules/auth/handlers/refresh-token.ts
> +  const userData = await validateRefreshToken(refreshToken);
Не очень хороший выбор имени с учетом того, что у тебя потом появляется еще и user. Лучше назвать переменную наподобие userTokenPayload

2022-04-20 06:25 UTC, khikhlun-itransition commented on src/middleware/validateAuth.ts
> +import { NextFunction, Request, Response } from 'express';
Этот мидвейр должен лежать на уровне src\modules\auth, так как нигде кроме этого модуля использоваться не будет

2022-04-20 06:51 UTC, PVBalyuk commented on src/modules/auth/handlers/login.ts
> +  const isValidPass = await validatePassword(req.body.password, userEmailCheck.get().password);
done

2022-04-20 06:55 UTC, PVBalyuk commented on src/modules/auth/handlers/login.ts
> +  await Customer.update({ refreshToken: token.refreshToken }, { where: { email: req.body.email } });
done

2022-04-20 07:00 UTC, pvb-fs commented on src/modules/auth/handlers/login.ts
> +  res.status(200).json(`id${id} ${firstName} ${secondName} ${email} Refresh token - ${token.refreshToken}`);
done

2022-04-20 07:01 UTC, PVBalyuk commented on src/modules/auth/handlers/refresh-token.ts
> +  const email = user.get().email;
done

2022-04-20 07:02 UTC, pvb-fs commented on src/modules/auth/handlers/refresh-token.ts
> +  const userData = await validateRefreshToken(refreshToken);
done

2022-04-20 07:03 UTC, pvb-fs commented on src/middleware/validateAuth.ts
> +import { NextFunction, Request, Response } from 'express';
done

2022-04-20 07:07 UTC, khikhlun-itransition approved these changes

2022-04-20 07:08 UTC, merged